server:
  port: 8002
spring:
  application:
    name: igo-product-test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/igo_product
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:cn/qctj/igo/mapper/*Mapper.xml
  type-aliases-package: cn.qctj.igo.domain,cn.qctj.igo.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true