server:
  port: 8010
  max-http-header-size:1024000
  tomcat:
    max-http-post-size:1024000
spring:
  application:
    name: igo-common
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true